# Jekyll Konfigurationsdatei
# -------------------------

# Das Standard-Theme f端r GitHub Pages

# Titel deiner Agentur-Website
title: Wachswerk

# Eine kurze Beschreibung
description: Performance Marketing f端r lokale Dienstleister und E-Commerce Shops.

# CSS-Link f端r das Styling hinzuf端gen
header_pages:
  - /assets/css/style.css
